FROM --platform=$TARGETPLATFORM ubuntu/dotnet-aspnet:7.0_edge AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["UT-GraphicsDemo.csproj", "."]
RUN dotnet restore "UT-GraphicsDemo.csproj" 
COPY . .
RUN dotnet build "UT-GraphicsDemo.csproj" -c Debug --no-self-contained -o /app/build

FROM build AS publish
RUN dotnet publish "UT-GraphicsDemo.csproj" -c Debug --no-self-contained -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
RUN apt-get update
RUN apt-get install -y libfontconfig1
ENTRYPOINT ["dotnet", "UT-GraphicsDemo.dll"]